### ISSUE TITLE
你好，官网的这个比赛是今年的比赛吗

### ISSUE THREAD

**Issue by ghost** [PRS-Organization/PRS-Trial-Version#1]
https://prsorg.github.io/challenge.html

CVPR2024的workshop之一，我点进去他显示是5月之前宣布。
这个比赛还有效吗，是今年的还是已经结束的？
如果还有效，大概什么时间举办？
谢谢
========================================
https://prsorg.github.io/challenge.html

One of the workshops for CVPR2024, I clicked on it and it showed that it was announced before May.
Is this competition still valid, is it this year's or has it already ended?
If it's still valid, when will it be held approximately?
thanks

**Comment by zhqunxu** [comment]
We will maintain a long-term leaderboard. Due to the policy review, we plan to release more details in the coming days.
